name: "Tests"
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

    branches:
      - master
    tags:
      - ci
      - tests  
    paths-ignore:
    - .gitignore
    - LICENSE.md
    - README.md

  push:
    branches:
    - master
    paths-ignore:
    - .gitignore
    - LICENSE.md
    - README.md

jobs:
  precommit:
    runs-on: ubuntu-latest
    container: ghcr.io/hadolint/hadolint:latest-debian
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Hooks
        shell: bash
        run: |
          python -m pip install pre-commit 
          pre-commit install
          pre-commit run --all-files